UNPQ-89 fix: leaks and throw message
crash-webserve/webserve pull request #34
Opened 2022-06-06 05:33 UTC by mike2ox

## Description
- 웹서브 내에 메모리 누수에 대해 해결
- throw로 전달할 message 작성

## Test
[setup]
- webserve 디렉토리에서 test
- configuration file, constant.hpp 정보는 test환경에 맞게 수정해주셔야 합니다.

[client1] `./webserve ./conf/sample.conf`
[client2] `while true; do; sudo leaks --atExit -- ./webserve conf/sample.conf; sleep 0.5; done;`

2022-06-06 06:12 UTC, Liemani approved these changes
확인했습니다.
고생하셨습니다!

2022-06-06 08:27 UTC, komskoms requested changes
exception 부분 정정하고 approve하겠습니다!

2022-06-06 08:27 UTC, komskoms commented on Connection.cpp
> +        throw std::runtime_error("listen() Failed");
회의 때 이야기했듯, runtime_error 사용할 경우, 서버 실행상태를 유지하는데, 초기화 실패의 경우이므로 다른 예외로 처리하여, 서버블록 밖의 catch에서 처리되도록 하는 편이 맞겠습니다

2022-06-06 09:54 UTC, mike2ox commented on Connection.cpp
> +        throw std::runtime_error("listen() Failed");
수정완료했습니다 :)

2022-06-07 05:44 UTC, komskoms approved these changes

2022-06-07 05:44 UTC, merged